/**
 * Codegen: emit `src/theme.css` from the token registries in `tokens.ts`.
 *
 * theme.css is GENERATED — never hand-edit it. Change `tokens.ts` and re-run:
 *   npx tsx src/theme/generateThemeCss.ts
 *
 * Output structure:
 *   :root { <dark core tokens> <semantic aliases> --gradient-brand <glow tokens> }
 *   [data-theme="light"] { <light core tokens> }   // aliases inherit via var()
 *   :root { font-size: 16px } [data-density="compact"] { font-size: 14.5px }
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  darkTokens,
  lightTokens,
  semanticAliases,
  gradientBrand,
  densityRootFontPx,
} from './tokens.js';

/** Glow tokens preserved from the original index.css :root block. */
const glowTokens: Readonly<Record<string, string>> = {
  '--glow-blue': '0 0 20px rgba(88,166,255,0.25)',
  '--glow-green': '0 0 20px rgba(63,185,80,0.25)',
  '--glow-red': '0 0 20px rgba(248,81,73,0.25)',
  '--glow-amber': '0 0 20px rgba(210,153,34,0.25)',
};

const INDENT = '  ';

/** Render a record of CSS custom properties as indented `--k: v;` lines. */
function renderVars(vars: Readonly<Record<string, string>>): string {
  return Object.entries(vars)
    .map(([key, value]) => `${INDENT}${key}: ${value};`)
    .join('\n');
}

const header =
  '/* AUTO-GENERATED by src/theme/generateThemeCss.ts — edit tokens.ts, not this file. */';

const rootBlock = [
  ':root {',
  renderVars(darkTokens),
  renderVars(semanticAliases),
  `${INDENT}--gradient-brand: ${gradientBrand};`,
  renderVars(glowTokens),
  '}',
].join('\n');

const lightBlock = ['[data-theme="light"] {', renderVars(lightTokens), '}'].join(
  '\n',
);

const densityBlock = [
  `:root { font-size: ${densityRootFontPx.spacious}px; }`,
  `[data-density="compact"] { font-size: ${densityRootFontPx.compact}px; }`,
].join('\n');

const css = `${header}\n\n${rootBlock}\n\n${lightBlock}\n\n${densityBlock}\n`;

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// __dirname === <repo>/src/theme → theme.css lives one level up in src/.
const outPath = resolve(__dirname, '..', 'theme.css');

writeFileSync(outPath, css, 'utf8');

console.log(`[generateThemeCss] wrote ${outPath} (${css.length} bytes)`);
